apiVersion: v1
kind: Pod
metadata:
  name: volume-cm
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: contents
      mountPath: /usr/share/nginx/html
  volumes:
  - name: contents
    configMap:
      name: sample-file-cm
