apiVersion: v1
kind: Pod
metadata:
  name: volume-cm
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: nginx-conf
      mountPath: /etc/nginx/nginx.conf
      subPath: sample.conf
  volumes:
  - name: nginx-conf
    configMap:
      name: sample-file-cm
